# Generated by Django 4.1.2 on 2022-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TeamWork", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Today_Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
