# Generated by Django 4.1.2 on 2022-10-31 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("TeamWork", "0002_today_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="today_todo",
            name="Date_Created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
