# Generated by Django 4.1.2 on 2022-11-02 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("TeamWork", "0002_today_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="today_todo",
            name="Created_by",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="TeamWork.profile",
            ),
        ),
        migrations.AddField(
            model_name="today_todo",
            name="Date_Created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
