# Generated by Django 4.1.2 on 2022-11-03 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("TeamWork", "0003_today_todo_created_by_today_todo_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="today_todo",
            name="Created_by",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
